api_platform:
    show_webby: false
    http_cache:
        invalidation:
            enabled: true
            #varnish_urls: []
        public: ~

    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']  
        pagination_enabled: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 10
    
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    #patch_formats:
    #    json: ['application/merge-patch+json']
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']   
    #    html:
    #        mime_types: ['text/html']     
    swagger:
        versions: [3]         
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Validation exception
        # ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

        # Custom mapping
        App\Exception\DisplayCustomerWithoutAuthorizationException: 401
        App\Exception\CustomerNotExistException: 404
        App\Exception\ProductNotExistException: 404

    error_formats:
        jsonproblem:
            #mime_types: ['application/problem+json']
            mime_types: ['application/json']
            

        jsonld:
            mime_types: ['application/ld+json']